
services:
  nginx:
    build: ./nginx
    networks:
      - files
    ports:
      - 80:80
    depends_on:
      - app
    environment:
      - VIRTUAL_HOST=files.cristibtz.live

  app:
    restart: always
    container_name: flask_app
    build: ./Project
    links:
      - db:db
    env_file:
      - .env
    environment:
        DEBUG: True
        POSTGRES_DB: ${POSTGRES_DB}
        DATABASE_PORT: 5432
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./Project:/app
    depends_on:
      - db
    command: > 
      sh -c "python3 ./create_db.py && gunicorn -w 8 -b :5000 wsgi:app --worker-class=gevent --timeout=60"

  db:
    restart: always
    container_name: postgres_db
    image: postgres:latest
    volumes: 
      - postgres-data:/var/lib/postgresql
    env_file:
      - .env
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  postgres-data:

networks:
  files:
    external: true
    name: files_default