name: File Uploader CI/CD Pipeline
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: file-uploader
      REGISTRY: docker.io/${{ secrets.DOCKER_USERNAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to container registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build Docker image
      run: docker build -t $REGISTRY/$IMAGE_NAME:latest ./Project
    
    - name: Push Docker image
      run: docker push $REGISTRY/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check K8s cluster connectivity
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods -n file-uploader
      
    - name: Restart pod
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: delete pod -l app=file-uploader -n file-uploader
    
    - name: Verify deployment
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: rollout status deployment/file-uploader -n file-uploader    