name: File Uploader CI/CD Pipeline
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: file-uploader
      REGISTRY: docker.io/{{ secrets.DOCKER_USERNAME }}

    steps:
    - name: Checkout code
      run: actions/checkout@v3

    - name: Login to container registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build Docker image
      run: docker build -t $REGISTRY/$IMAGE_NAME:latest .
    
    - name: Push Docker image
      run: docker push $REGISTRY/$IMAGE_NAME:latest